name: Linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          # dir: '${{ github.workspace }}/extern/' # Default to $RUNNER_WORKSPACE
          install-deps: 'true'
          setup-python: 'false'
        #   archives: 'qtbase'
        #   cache: 'true'
        #   cache-key-prefix: 'install-qt-action'

      - name: Build Qt::QtWidgets
        run: zef --/test install .

      - name: Test Qt object
        run: |
          # Install a pseudo X11 screen
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
          # Run the pseudo X11 screen
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          echo "Pseudo screen installed"
          # Run the tests
          for i in t/*; do raku $i; done

